export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const REQUEST_DEVICES = 'REQUEST_DEVICES';
export const RECEIVE_DEVICES = 'RECEIVE_DEVICES';
export const INVALIDATE_DEVICES = 'INVALIDATE_DEVICES';